# Generated by Django 3.2.9 on 2021-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
