# Generated by Django 3.2.9 on 2021-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
